### ISSUE TITLE
Homer Iliad Book 16

### ISSUE THREAD

**Issue by egreven** [cltk/grc_text_perseus#1]
For Homer's Iliad Book 16 it is a repeat of the text from Book 17. I can see about updating it.

**Comment by diyclassics** [comment]
@egreven Thanks for the Issue submission. Can you link to the specific file that has the repetition? Thanks!

**Comment by diyclassics** [comment]
@egreven And fwiw if you are looking to work with the text of the Iliad (i.e. not with any of the Perseus specific metadata), it may be easier to work with the Tesserae texts in the CLTK Readers package, cf. https://github.com/diyclassics/cltk_readers. The examples in the docs (and notebook) are for Latin texts, but the api is the same for the Ancient Greek texts. I'll try to update the docs with Greek examples soon.

**Comment by diyclassics** [comment]
@egreven Found the text you are referring to https://github.com/cltk/grc_text_perseus/blob/master/json/homer__iliad.json. Will have a fix shortly.

**Comment by diyclassics** [comment]
In case it helps—here is a gist with the code I used to output Book 16 content as json using CLTK Readers: https://gist.github.com/diyclassics/8c531175c0a44bfafd3523ae0f60ebe0

**Comment by egreven** [comment]
Thank you for the code and link to the Tesserae texts.
